# Generated by Django 3.1.4 on 2020-12-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
    ]
